def print_stand
    if @wrong_guess == 0
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 1
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 2
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O\n"
        print "  |          | \n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 3
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O\n"
        print "  |          |\n"
        print "  |          |\\ \n"
        print "  |          |\n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 4
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O\n"
        print "  |          |\n"
        print "  |         /|\\ \n"
        print "  |          |\n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 5
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O\n"
        print "  |          |\n"
        print "  |         /|\\ \n"
        print "  |          |\n"
        print "  |         /\n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    elsif @wrong_guess == 6
        print "  ------------\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          |\n"
        print "  |          O\n"
        print "  |          |\n"
        print "  |         /|\\ \n"
        print "  |          |\n"
        print "  |         / \\   \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "  |          \n"
        print "-----\n"
    end
end